name: parabeac_core
description: A starting point for Dart libraries or applications.
version: 2.4.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^2.2.0
  archive: ^3.1.2
  json_serializable: ^3.5.0
  build_runner: ^1.10.0
  mockito: ^4.1.1
  hex: ^0.1.2
  build: ^1.3.0
  logger: ^0.8.3
  uuid: ^3.0.0
  quick_log: ^1.1.3
  http2: ^1.0.1
  recase: "^3.0.0"
  tuple: ^1.0.3
  path: ^1.6.0
  file: ^6.1.2
  pbdl:
    git: 
      url: https://github.com/Parabeac/pbdl.git
      ref: master
  directed_graph: ^0.2.3
  sentry: ^6.2.2
  yaml_modify: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_config: ^0.4.2
# dependency_overrides:
#   analyzer: '0.39.14'
